
import type { Metadata } from "next";

import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Provider from "@/Provider";



export const metadata: Metadata = {
  title: "MultiCart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
       <Provider>
          {children}
          </Provider></body>
    </html>
  );
}
